### ISSUE TITLE
Error while shutting down the bot

### ISSUE THREAD

**Issue by FedGiannetto** [pietroalbini/botogram#1]
Here's the error: http://paste.ubuntu.com/11841659/ .

The bot runs smoothly until I press Ctrl+C to close it.

**Comment by pietroalbini** [comment]
That exception is not an error, but simply points out that the program was stopped with `ctrl`+`c`. On Linux that's handled by catching SIGINT globally, but seems that Windows behaves differently.

I'll see how I can catch KeyboardInterrupt properly on that OS.
