### ISSUE TITLE
ChatMixin fails with User objects due to AttributeError

### ISSUE THREAD

**Issue by patternspandemic** [pietroalbini/botogram#21]
A regression in `ChatMixin._get_call_args` introduced by [2245bd6](https://github.com/pietroalbini/botogram/commit/2245bd617cceb276d56a2d65d8fa0c4a0eb9100f#diff-f0c442737721b2b7db83787f960429b5R40) causes an `AttributeError: 'User' object has no attribute 'type'` when attempting to use any `send*` method on `User` objects.

```python
user = botogram.User(
    {'id': 123, 'first_name': 'User'},
    api=bot.api
)
user.send('Anything...')
```
```
File "..../botogram/objects/mixins.py", line 33, in _get_call_args
    chat_id = self.username if self.type == "channel" else self.id
AttributeError: 'User' object has no attribute 'type'

```

Cheers, Brad

**Comment by pietroalbini** [comment]
I absolutely need to write more tests. I'll fix this later.
