### ISSUE TITLE
Cannot start shared-memory branch on Windows

### ISSUE THREAD

**Issue by tsculpt** [pietroalbini/botogram#3]
Hi Pietro.

Master at ba226c seems fine. However I cannot start the shared-memory branch.

With attempting to run a stripped bot (just passing the api key), it may run but does not respond (some kind of race condition?). Other times, setting one simple component or the about / owner bot attribute, I get any of the three errors pasted bellow:
```
...
\runner\__init__.py", line 85, in _boot_processes
    worker.start()
  File "C:\Python34\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python34\Lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python34\Lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Python34\Lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python34\Lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python34\Lib\multiprocessing\connection.py", line 940, in reduce_pipe_connection
    dh = reduction.DupHandle(conn.fileno(), access)
  File "C:\Python34\Lib\multiprocessing\connection.py", line 170, in fileno
    self._check_closed()
  File "C:\Python34\Lib\multiprocessing\connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```
```
...
\runner\__init__.py", line 85, in _boot_processes
    worker.start()
  File "C:\Python34\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python34\Lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python34\Lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Python34\Lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python34\Lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'weakref'>: attribute lookup weakref
on builtins failed
```
```
...
\runner\__init__.py", line 85, in _boot_processes
    worker.start()
  File "C:\Python34\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python34\Lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python34\Lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Python34\Lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python34\Lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function BaseManager._finalize_manager at 0
x03214F18>: attribute lookup _finalize_manager on multiprocessing.managers failed
```
Hope this helps,
Brad

**Comment by tsculpt** [comment]
Toying around, I replaced the `SharedMemoryManager` 's `_manager` attribute with `multiprocessing.Manager()` and arrived at a different, possibly helpful error:

```
20:03.53 -   DEBUG   - Component botogram just loaded into the bot
20:03.55 -   DEBUG   - Component botogram just loaded into the bot
20:03.57 -   INFO    - The botogram runner is booting up.
20:03.57 -   INFO    - Press Ctrl+C to exit.
Traceback (most recent call last):
...
\runner\__init__.py", line 56, in run
    self._shared_memory.start()
  File "C:\.....\botogram\runner\shared.py", line 60, in start
    self._manager.start()
  File "C:\Python34\Lib\multiprocessing\managers.py", line 475, in start
    assert self._state.value == State.INITIAL
AssertionError
```
Brad

**Comment by pietroalbini** [comment]
Just a random note, I've figured out how to simulate the Windows behavior on my Linux machine, so it should be easier for me to simulate what's going wrong.

**Comment by pietroalbini** [comment]
> Toying around, I replaced the SharedMemoryManager 's _manager attribute with
> multiprocessing.Manager() and arrived at a different, possibly helpful error:

No, that's because ``Manager()`` automatically calls the ``start()`` method, and obviously you can't start an already-started manager.

**Comment by tsculpt** [comment]
Ah, I see that now.
> I've figured out how to simulate the Windows behavior on my Linux machine,
Very good, no doubt this will be more efficient than my actions. :)

**Comment by pietroalbini** [comment]
I think I've found the problem (hopefully the only one).

When the runner's shared memory driver is serialized, it [requires to the master process a new communication queue][1]. Unfortunately, the master process starts accepting shared memory's commands [after all processes are booted up][2]. This doesn't cause any problem on Linux and OSX, but on Windows the driver object is serialized while booting up processes, so a deadlock happens.

Now I'm just tired, tomorrow I'll see how I can fix this problem (I wish this doesn't require a brand new process just for this thing).

Pietro.

[1]: https://github.com/pietroalbini/botogram/blob/c338c2181ece16ac5243072853a65f2f29080d68/botogram/runner/shared.py#L77
[2]: https://github.com/pietroalbini/botogram/blob/c338c2181ece16ac5243072853a65f2f29080d68/botogram/runner/__init__.py#L62

**Comment by pietroalbini** [comment]
Just a quick note, I've managed to get over the the deadlock. Unfortunately, a new error came out just now :-(

**Comment by tsculpt** [comment]
That's good news. I'm interested in seeing how you got around it.

**Comment by pietroalbini** [comment]
I've pushed 10833fa, which doesn't bring full compatibility (there is the error I mentioned yesterday), but resolves the ones you reported I was able to reproduce. Can you try directly on Windows which errors it's giving?

**Comment by tsculpt** [comment]
Here it is:
```
05:08.19 -   DEBUG   - Component botogram just loaded into the bot
05:08.21 -   INFO    - The botogram runner is booting up.
05:08.21 -   INFO    - Press Ctrl+C to exit.
05:08.22 -   DEBUG   - Component botogram just loaded into the bot
05:08.24 -   DEBUG   - Component botogram just loaded into the bot
05:08.26 -   DEBUG   - Shared process is ready! (pid: 7048)
Traceback (most recent call last):
  File "C:\Python34\Lib\multiprocessing\queues.py", line 242, in _feed
    obj = ForkingPickler.dumps(obj)
  File "C:\Python34\Lib\multiprocessing\reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "C:\Python34\Lib\multiprocessing\queues.py", line 57, in __getstate__
    context.assert_spawning(self)
  File "C:\Python34\Lib\multiprocessing\context.py", line 347, in assert_spawning
    ' through inheritance' % type(obj).__name__
RuntimeError: Queue objects should only be shared between processes through inheritance
```

**Comment by pietroalbini** [comment]
Perfect. Later in the afternoon I'll try to migrate from queues to pipes.

**Comment by pietroalbini** [comment]
Current status: I can't find a way to transfer pipes to different processes via other pipes. Uff.

**Comment by tsculpt** [comment]
Hmm, seems to be a tough problem. I have set up the docker tool chain in order to further develop. Perhaps with time a solution to this process issue will present itself. Thank you for looking into it nonetheless.

Brad

**Comment by pietroalbini** [comment]
Yesterday I started implementing the interprocess communication with standard sockets. If this doesn't work (but I think it will) I'll probably drop Windows suppory, since I'm wasting too much time on this, delaying new features.

**Comment by tsculpt** [comment]
Completely understandable. I'm looking forward to what else you come up with. Cheers.

**Comment by pietroalbini** [comment]
Seems that the interprocess communication with sockets works fine. Now I'll start figuring out how to correctly use it with the multiprocessing's Managers, but I'm optimistic this time.

**Comment by pietroalbini** [comment]
By the way, I'm a bit busy, but I'm still working on this :)

**Comment by pietroalbini** [comment]
Hey @tsculpt, do you mind checking if the latest commit on the ``socket-ipc`` branch is working?

Thanks,
Pietro.

**Comment by pietroalbini** [comment]
A friend of mine tested the changes on Windows, and all works flawlessy!

**Comment by tsculpt** [comment]
Awesome work Pietro! I'm looking forward to release. Cheers.
