### ISSUE TITLE
The future of botogram

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/botogram#52]
Don't worry, botogram is not going to go away, this is about extending it!

Currently, botogram is strictly tied to the Telegram bots API. There is no problem with that, I started botogram with Telegram as the only target and I'm not going to leave it anytime soon. The thing is, the bots landscape is rapidly mutating, and more and more platform are adopting some kinds of API. Other than that, I want to avoid to lock everything into one single platform, because in the remote eventuality Telegram turns evil I don't want to see all this work wasted.

The thing I'm thinking about now is turning botogram into a more generic framework for bots, while keeping the same API. Fortunately, most of the logic of botogram is actually detached from the Telegram API, so it's simple to call an abstraction layer instead of the API directly.

I think this is the way to go, in order to embrace more platforms and guarantee a future for botogram even if Telegram slows down. But any opinion is highly appreciated!

**Comment by patternspandemic** [comment]
Hi Pietro.

Making botogram a generic framework makes sense. What other available platforms do you have in mind? Are you aware of any others that are more open than Telegram's at this time?

In the near term, I see new platforms being targeted toward business, with their APIs being at least somewhat subscription driven and more 'locked down'. This is of course not a reason _not_ to support them via botogram, though I cannot see moving from Telegram unless some key component critical to a bot's working/purpose is only available via another platform. In this case, the only things I can think of would be some kind of business intelligence agent (think IBM Watson, Cortana, etc), better/easier integration with other 'wares owned by another platform, or simply the platform reach is greater (more people utilize it). The open API landscape already greatly helps with the first two, and allows you to stay with Telegram.

In any case, I am happy there are more platforms arriving. They will force each other to add more and better features, and hopefully keep each other honest. That said, it's simply good software development to abstract away Telegram's API, and I think you've done a nice job with that already.

If it were me, I would continue on to 1.0 and make a solid Telegram framework that's already in good shape to be generalized and supportive of multiple frameworks.

Brad

**Comment by pietroalbini** [comment]
> Making botogram a generic framework makes sense. What other available platforms do you have in mind? Are you aware of any others that are more open than Telegram's at this time?

I'm looking around at the other APIs out there, but I want to abstract the framework even if Telegram is the only decent one, because I don't want to be locked in a platform.

> This is of course not a reason not to support them via botogram, though I cannot see moving from Telegram unless some key component critical to a bot's working/purpose is only available via another platform.

But the thing this will allow you to do is something like:

```python
bot.add_provider("telegram", "122324:slkdnlflkzsbdflkblkfakbjkas")
bot.add_provider("slack", "their_api_key")
```

The botogram structure allows right now to have multiple processes fetching updates from the upstream server, and having them connecting to different providers isn't that difficult. So, you will be able to have support to multiple platforms in the same instance of your bot (if you're not using APIs available only in one of the platforms).

> If it were me, I would continue on to 1.0 and make a solid Telegram framework that's already in good shape to be generalized and supportive of multiple frameworks.

I don't plan to add other drivers right away (I prefer implement the Telegram API in a good way), but doing that post-1.0 will be much harder than currently.

**Comment by pietroalbini** [comment]
I don't think I will ever do this.
