### ISSUE TITLE
Add ability to edit messages

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/botogram#55]
The recent API change allowed to edit existing messages sent by bots. There should be some new methods to edit messages also in botogram.

Because of that, all the `send*` methods should also return the instance of the message you send.

```python
message = chat.send("This message will destruct itself in 1 second")
time.sleep(1)
message.edit("*BOOM*")
```

```python
message = chat.send_photo("myphoto.png", caption="A caption")
message.edit_caption("I'm changed!")
```

**Comment by MarcoBuster** [comment]
How I can download this feature?

**Comment by pietroalbini** [comment]
It's not yet implemented.

**Comment by MarcoBuster** [comment]
:cry:
