### ISSUE TITLE
Implement keyboards support

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/botogram#6]
Keyboards are one of the best parts of the Telegram bots API, but they are nasty to implement in a generic and reliable way, because botogram needs to call the right hook when someone replies, filter all the incoming requests for actual replies and maintain an internal registry of which keboards are active at the moment.

```python
@bot.keyboard(permanent=True)
def my_keyboard(chat, message, user, answer):
    chat.send("You replied with %s" % answer)

@bot.command("ask")
def ask_command(chat, message, args):
    kb = my_keyboard.prepare()
    kb.row("Yes", "Not")
    chat.send("Hey @pietroalbini, are you OK today?", extra=kb)
```

- [x] Add support for shared memory (issue #4)
- [x] Add support for timers (issue #5)
- [ ] Implement ForceReply
- [ ] Implement keyboards on top of ForceReply
- [ ] Document the whole thing

*This issue tracks the progress on this feature.*

**Comment by pietroalbini** [comment]
If you have ideas for a better API please share it!

**Comment by tsculpt** [comment]
Nice. I was hoping there would be an API around the keyboards, and here it is! It sounds like the shared memory will keep a kind of session for commands that us keyboards.

Also, perhaps integrate easy inclusion of emoji into reply keyboards?

Awesome. Brad

**Comment by pietroalbini** [comment]
Yes, shared memory was firstly implemented because it's the only way to store which keyboards are active in a worker-indipended way. And timers are needed to clean up old keyboards.

What do you mean with emoji support? Something like ``botogram.SMILE``? You can already paste any emoji from telegram in a Python string.

**Comment by tsculpt** [comment]
> You can already paste any emoji from telegram in a Python string.

Right, scratch that request. Hah!

**Comment by pietroalbini** [comment]
This is the latest idea I have about the API, but I'm not fully sold to it yet. Any input is welcomed!

```python
@bot.keyboard(permanent=True)
def my_keyboard(chat, message, user, answer):
    chat.send("You replied with %s" % answer)

@bot.command("ask")
def ask_command(chat, message, args):
    kb = my_keyboard.prepare()
    kb.row("Yes", "Not")
    chat.send("Hey @pietroalbini, are you OK today?", extra=kb)
```

**Comment by patternspandemic** [comment]
Hi Pietro,

I (formerly tsculpt) am glad to see keyboards will make it into the initial release.

Looking at your API idea above, I am not seeing how the `my_keyboard` hook is tied to the `ask_command`. Also what is the `permanent` keyword argument referring to in the decorator?

Here are some quick thoughts I had on how keyboards might work:

- Preferably, keyboards and the hooks which process their replies are defined separately for re-usability.
- A hook could define a session with a user that always either:
  * Sends a new prompt with a keyboard (multi-keyboard interactions), prompting for the next step in the decision tree
  * Ends the session without error performing some final result or work
  * Exits the session in error gracefully (perhaps by timing out)
  
  With this, there would also be a need for somehow tracking all replies of the session to execute the correct step in the hook quickly and correctly.
- Perhaps these session hooks could be implemented with the help of python generators and/or coroutines
- The system could allow for going 'back' to the previous keyboard, like many UIs allow. I suppose this would simply be a keyboard option that simply popped off the 2 most recent choices made in the session (back, and the choice made proir), thus again sending the the correct prompt and keyboard based on the resulting session choices.

Nevertheless, I'll continue to think about this. Let me know what you think.
Cheers, Brad

**Comment by pietroalbini** [comment]
Ok, let me explain what I meant with that API.

First of all, I don't want to put navigation menus in the same API as keyboards, because keyboards can also be used for other reasons, and I don't want to limit the things you can build with them. I plan to design a separated API for navigation, but after the initial release.

That code snippets defines a keyboard and a command to send it. Keyboards are defined with an hook, which is called when a button of the keyboard is pressed (botogram will automatically detect if the user sends a generic reply or presses a button, and it will handle timeouts). Then, the command prepares the keyboard, adds all the wanted rows and sends it.

The arguments of the `@bot.keyboard` decorator are [the one Telegram supports](https://core.telegram.org/bots/api#replykeyboardmarkup), partially renamed because I don't like their naming scheme so much: `permanent` is the inverse of `one_time_keyboard`, `resize` is `resize_keyboard` and `everyone` is the inverse of `selective`.

Maybe I'll put the rows definition as decorators, but I don't want that to be the only way to define rows, because you might need dynamic rows (an example is `@botfather`). Hypothetical API:

```python
@bot.keyboard(permanent=True)
@botogram.row("1", "2", "3", "4", "5")
def my_keyboard(chat, message, answer):
    pass
```

**Comment by patternspandemic** [comment]
```python
    kb = my_keyboard.prepare()
```
Err, well it was in front of me all along. Got it.

I agree with the renamed args, as well.

I like the idea of using a decorator for rows so the keyboard's args, rows, and callback are all in one place. It could serve to define the default row layout which can then be altered in commands from `kb.rows` when a dynamic option is required.

**Comment by pietroalbini** [comment]
Yeah, that's the plan. I'm only worried it can be annoying to use everytime `@botogram.row`, as I removed `@botogram.pass_*` for that reason.

**Comment by patternspandemic** [comment]
Perhaps extend `@bot.keyboard` with an optional kwarg instead of using another decorator? It could accept various row representations, or strings naming common presets.

```python
custom_kb = ['Yes', 'No', 'Maybe']
@bot.keyboard(permanent=True, layout=custom_kb)
#  or...
@bot.keyboard(permanent=True, layout='yes_no')
```

**Comment by MarcoBuster** [comment]
I love keyboards :)
Please add keyboards fast :smiley:

**Comment by pietroalbini** [comment]
This issue is replaced by issue #66.
