### ISSUE TITLE
Botogram crash on linux

### ISSUE THREAD

**Issue by MarcoBuster** [pietroalbini/botogram#62]
Hi,
After 30 seconds before starting the bot, the bot doesn't reply to commands. This in Linux, in Windows it's works fine. Please fix it ASAP. 
Thanks,
Marco

**Comment by pietroalbini** [comment]
Is it still processing backlog? Try run it with the ``BOTOGRAM_DEBUG`` environment variable, like so:

```
$ export BOTOGRAM_DEBUG=1
$ python3 yourbot.py
```

If it's skipping the backlog just wait, the new algorithm is faster but there isn't too much I can do, but if it's just not responding paste the output here.

**Comment by thesharp** [comment]
My bot replies to commands right away. Doesn't look like a regression.

**Comment by pietroalbini** [comment]
That lag is probably due to an huge backlog, but he might have hit a performance regression in the recently-introduced new updates fetching system.

I should probably notify the user about backlog processing by the way.

**Comment by MarcoBuster** [comment]
Fixxed

**Comment by pietroalbini** [comment]
Well, I guess that was just a bunch of backlog.
