### ISSUE TITLE
Reliability

### ISSUE THREAD

**Issue by thanosilva** [pietroalbini/botogram#88]
The bot  stops to respond after some time, i need to send three or more comands / msgs in sequence for it answer.

**Comment by MarcoBuster** [comment]
I don't have this problem. Send your code.

**Comment by pietroalbini** [comment]
Closing due to author inactivity. It's not possible to debug the problem without any code or log.

If you experience this again, try to reproduce the issue in a reliable way and attach the code and log, thanks!
